services:
  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    volumes:
      - vault-data:/vault/data
      - ./../config/vault:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: ["vault", "server", "-config=/vault/config/config.hcl"]

volumes:
  vault-data: